### ISSUE TITLE
Which version of checkpoint is better for in-the-wild scenes

### ISSUE THREAD

**Issue by MooreManor** [wkom/VirtualPose#10]
For better inference performance on in-the-wild scenes, which version of the checkpoint should I choose?

![image](https://github.com/wkom/VirtualPose/assets/49632327/d35ca2b3-dc72-49b9-bbe2-dbde6194b1ee)

**Comment by rigved-sanku** [comment]
Did you get the answer?
Even I am interested to know

**Comment by MooreManor** [comment]
@rigved-sanku 
Sorry, I didn't know either. 😢
