### ISSUE TITLE
MuPoTS-3D cameas.pkl

### ISSUE THREAD

**Issue by shawnpark07** [wkom/VirtualPose#3]
Hi, there
Thanks for your elaborated work :)

How did you unnormalize root depths for testing MuPoTS-3D dataset?
I mean, how did you get the focal lengths data of it?

**Comment by shawnpark07** [comment]
Never mind, I found it

**Comment by leoisufa** [comment]
Hi, I want to download the file named 'cameras.pkl', but the link may be disable. can u tell me where to get this file? thank u
