### ISSUE TITLE
MuPoTS google driver link and model weight

### ISSUE THREAD

**Issue by leoisufa** [wkom/VirtualPose#5]
Hi, thanks for your great work!

I have a question about the google driver link of MuPoTS that has been not found 404. By the way, can u provide the model weight for evaluating?

**Comment by wkom** [comment]
Hi, you can get the new google driver link of MuPoTS from [RootNet](https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE), and the model weight willing be coming soon.
